### ISSUE TITLE
[FT] [UI] User definied color background for slices

### ISSUE THREAD

**Issue by kamirr** [Schneegans/Gnome-Pie#133]
Hi!

I'm using Gnome-Pie 0.6.9, while using numix icon theme background for terminal icon doesn't change color while being focused. I understand that this color is calculated and making exception wouldn't be nice, so adding option to manually set that color would be the best one. At least I think so.

**Comment by Simmesimme** [comment]
Hi there!

I understand your problem, but I think that it is a pretty rare problem. It occurs only with a few icons and the only with a few Gnome-Pie themes. Added such an option to every slice would be a bit confusing since there are many themes which do not use such a color at all, wouldn't it?

The only thing I could imagine is to define a fallback color in the theme of Gnome-Pie which should be used if the saturation of the icon's color is too low... but I'm not very happy with this solution either...

What do you think?

**Comment by KoczurekK** [comment]
I would add switch "use default background color" set by default to "true" under the "Is Quick Action" switch and show color picker widget when user decides to change color. In my opinion it could keep UI clean and readable.
Also Steam and gnome-screenshot icons appear to have this problem with Numix icon theme, there are many black/grey icons in theme. :(

Great app btw, I gained sooo much free space on my screen. :D

**Comment by Schneegans** [comment]
As Gnome-Pie is now in _low-maintanance-mode_, I won't have the time to implement this. If you're using GNOME Shell and if you are still interested in this project, you could try out [Fly-Pie](https://github.com/Schneegans/Fly-Pie) which is a successor project of Gnome-Pie. With Fly-Pie, all appearance settings can be done in the preferences dialog -  there are no themes but rather some _presets_.
