### ISSUE TITLE
GNOME extension version

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [Schneegans/Gnome-Pie#147]
Since the news of Ubuntu ditching Unity and moving to GNOME, is it possible to make a Gnome-pie extension for GNOME?

It would be awesome :smile:

**Comment by Simmesimme** [comment]
What exactly do you mean? Nothing prevents you from using Gnome-Pie on Gnome :-)

**Comment by RicardoEPRodrigues** [comment]
Correct and I use it often! :smile: But for a new user going to the extensions website and clicking install would be amazing, other than that it would integrate better with the DE. Thank you for your time.

**Comment by Simmesimme** [comment]
Ahh, I understand now. But I think that this is impossible as Gnome Shell extensions are written in Javascript and Gnome-Pie is based on Vala. Or do you have some other idea in mind?

**Comment by RicardoEPRodrigues** [comment]
It would note be easy :smile: but to make the transition it would go something like:

* make the indicator using JS
* JS talks to a bash file
* bash file calls Vala

Is this possible?

**Comment by Simmesimme** [comment]
I put some thoughts into this idea... and the more I think about it, the more I actually like it. Especially because I do not see a future for Gnome-Pie on Wayland. A clean rewrite as Gnome Shell extension might be a good alternative... Maybe I will come up with a prove-of-concept implementation in the next weeks! Thanks for this idea!

**Comment by RicardoEPRodrigues** [comment]
I'd be happy to test it out when time comes.

**Comment by lestcape** [comment]
The performance will let a lot to say in my opinion, if this will be an extension of Gnome Shell. Also if it will be in that way it can block the compositor thread of Gnome Shell. This is the only thread that exist in Gnome Shell, where also is running the WM (Mutter).

Please note: In Gtk 3.0 you can merged a Clutter actor with a Gtk widget. Also in theory you can use an extension point and load the original widget that was wrote on Vala in gjs, but well this is in theory because of this issue: https://gitlab.gnome.org/GNOME/gjs/issues/109

It can be rendered also in a GPU if for example instead of Gtk 3.0 it will use Clutter or if it will use Gtk 4.0 when will be released (related to https://github.com/Simmesimme/Gnome-Pie/issues/151), but be an extension of Gnome Shell is different of use Clutter. Be an extension of Gnome Shell is what i think that will not be good for now. But is my opinion only...

**Comment by i-need-to-tell-you-something** [comment]
I wanted to also chime in with my viewpoint on this. I use Gnome-Pie on KDE and I bet many other people use it on some non-Gnome wm (window managers) and de (desktop environments) as well. Though I don't think you have to officially support any wm or de other than Gnome.
Of course if your OpenPie framework works fine without Gnome then *theoretically* someone can make a non-Gnome version of it - better than nothing.

Thanks a lot for making Gnome-Pie!

**Comment by Schneegans** [comment]
As we have [Fly-Pie](https://github.com/Schneegans/Fly-Pie) now, this can be closed, I guess :smile:
